[GLOBAL]
pants_version = "2.21.0.dev6"
backend_packages = [
  "pants.backend.python",
  "pants.backend.docker",
  "pants.backend.google_cloud_function.python",
]
colors = true
concurrent = true

[python]
interpreter_constraints = ['==3.11.*']
enable_resolves = true

[python-bootstrap]
search_path = ["<PYENV_LOCAL>"]

[docker]
use_buildx = true
